# Generated by Django 3.2.9 on 2022-02-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='RegistrationStu',
        ),
    ]
